import { useState, useEffect, useCallback } from 'react';
import type { TSPInstance } from '@/types/games/tsp';
import { getDailyChallenge } from '@/services/games/TSPService';

/**
 * Handles loading the daily TSP challenge from Firestore.
 * Challenges are pre-generated by a GitHub Actions cron job (scripts/generate-daily-challenge.js).
 *
 * Supports navigating to past days for practice mode.
 */

/** Returns a date as YYYY-MM-DD in UTC */
export const getDateString = (date: Date): string => {
    return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-${String(date.getUTCDate()).padStart(2, '0')}`;
};

/** Returns today's date as YYYY-MM-DD in UTC */
export const getTodayDateString = (): string => getDateString(new Date());

/** Format a UTC date string for display: "4 Mar 2026" (shown in local locale) */
export const formatDateLabel = (dateStr: string): string => {
    const [y, m, d] = dateStr.split('-').map(Number);
    const date = new Date(Date.UTC(y, m - 1, d));
    return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });
};

/** Get the previous day's date string (UTC) */
const getPrevDay = (dateStr: string): string => {
    const [y, m, d] = dateStr.split('-').map(Number);
    const date = new Date(Date.UTC(y, m - 1, d));
    date.setUTCDate(date.getUTCDate() - 1);
    return getDateString(date);
};

/** Get the next day's date string (UTC) */
const getNextDay = (dateStr: string): string => {
    const [y, m, d] = dateStr.split('-').map(Number);
    const date = new Date(Date.UTC(y, m - 1, d));
    date.setUTCDate(date.getUTCDate() + 1);
    return getDateString(date);
};

/**
 * Checks if points use normalized coordinates (0-1 range).
 * If all x and y values are <= 1, they are normalized and need to be scaled.
 */
const isNormalized = (instance: TSPInstance): boolean => {
    return instance.points.every(p => p.x <= 1 && p.y <= 1);
};

/** Scales normalized (0-1) coordinates to canvas pixel size */
const scaleToCanvas = (instance: TSPInstance, width: number, height: number): TSPInstance => {
    return {
        ...instance,
        points: instance.points.map(p => ({
            ...p,
            x: p.x * width,
            y: p.y * height,
        })),
    };
};

export const useTSPDailyChallenge = (canvasSize: { width: number; height: number }) => {
    const [selectedDate, setSelectedDate] = useState(getTodayDateString());
    const [instance, setInstance] = useState<TSPInstance | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [notFound, setNotFound] = useState(false);

    const isToday = selectedDate === getTodayDateString();

    const loadChallenge = useCallback(async (dateStr: string) => {
        setIsLoading(true);
        setNotFound(false);
        setInstance(null);

        try {
            const loaded = await getDailyChallenge(dateStr);

            if (loaded) {
                // Scale normalized coordinates (0-1) to canvas pixels if needed
                const w = canvasSize.width > 0 ? canvasSize.width : 800;
                const h = canvasSize.height > 0 ? canvasSize.height : 500;
                const scaled = isNormalized(loaded) ? scaleToCanvas(loaded, w, h) : loaded;
                setInstance(scaled);
            } else {
                setNotFound(true);
            }
        } catch (error) {
            console.error("Error loading daily challenge:", error);
            setNotFound(true);
        } finally {
            setIsLoading(false);
        }
    }, [canvasSize]);

    // Auto-load when canvas is ready or date changes
    useEffect(() => {
        if (canvasSize.width > 0 && canvasSize.height > 0) {
            loadChallenge(selectedDate);
        }
    }, [canvasSize.width, canvasSize.height, selectedDate, loadChallenge]);

    // ─── Date navigation ─────────────────────────────────────────

    const goToPrevDay = useCallback(() => {
        setSelectedDate(prev => getPrevDay(prev));
    }, []);

    const goToNextDay = useCallback(() => {
        setSelectedDate(prev => {
            const next = getNextDay(prev);
            // Can't go to the future
            if (next > getTodayDateString()) return prev;
            return next;
        });
    }, []);

    const goToToday = useCallback(() => {
        setSelectedDate(getTodayDateString());
    }, []);

    const canGoNext = getNextDay(selectedDate) <= getTodayDateString();

    return {
        instance,
        isLoading,
        isToday,
        notFound,
        selectedDate,
        canGoNext,
        dateLabel: formatDateLabel(selectedDate),
        reload: () => loadChallenge(selectedDate),
        goToPrevDay,
        goToNextDay,
        goToToday,
    };
};
